class NotAllowedExtensionError(Exception):
    ... 

class FileDoesNotExist(Exception):
    ... 


class FileBiggerThan1MBError(Exception): 
    ... 


class FileAlreadyExistError(Exception):
    ... 
